global:
  scrape_interval: 30s # Set the scrape interval to every 30 seconds.
  evaluation_interval: 30s # Evaluate rules every 30 seconds.

remote_write:
  - url: https://vm.monitoring.gcp.obol.tech/write
    authorization:
      credentials: $PROM_REMOTE_WRITE_TOKEN

scrape_configs:
  - job_name: 'nethermind'
    static_configs:
      - targets: ['nethermind:8645']
  - job_name: 'bn-lighthouse'
    static_configs:
      - targets: ['lighthouse:5054']
  - job_name: 'bn-nimbus'
    static_configs:
      - targets: ['nimbus:8008']
  - job_name: "charon-0"
    static_configs:
      - targets: ["node0:3620"]
  - job_name: "charon-1"
    static_configs:
      - targets: ["node1:3620"]
  - job_name: "charon-2"
    static_configs:
      - targets: ["node2:3620"]
  - job_name: "charon-3"
    static_configs:
      - targets: ["node3:3620"]
  - job_name: "charon-4"
    static_configs:
      - targets: ["node4:3620"]
  - job_name: "charon-5"
    static_configs:
      - targets: ["node5:3620"]
  - job_name: "charon-6"
    static_configs:
      - targets: ["node6:3620"]
  - job_name: "charon-7"
    static_configs:
      - targets: ["node7:3620"]
  - job_name: "charon-8"
    static_configs:
      - targets: ["node8:3620"]
  - job_name: "charon-9"
    static_configs:
      - targets: ["node9:3620"]
  - job_name: "vc0"
    static_configs:
      - targets: ["vc0-lighthouse:5064"]
  - job_name: "vc1"
    static_configs:
      - targets: ["vc1-teku:8008"]
  - job_name: "vc2"
    static_configs:
      - targets: ["vc2-lighthouse:5064"]
  - job_name: "vc3"
    static_configs:
      - targets: ["vc3-teku:8008"]
  - job_name: "vc4"
    static_configs:
      - targets: ["vc4-lighthouse:5064"]
  - job_name: "vc5"
    static_configs:
      - targets: ["vc5-teku:8008"]
  - job_name: "vc6"
    static_configs:
      - targets: ["vc6-lighthouse:5064"]
  - job_name: "vc7"
    static_configs:
      - targets: ["vc7-teku:8008"]
  - job_name: "vc8"
    static_configs:
      - targets: ["vc8-lighthouse:5064"]
  - job_name: "vc9"
    static_configs:
      - targets: ["vc9-teku:8008"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
